/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_easymorse_NdkHelloActivity */

#ifndef _Included_com_easymorse_NdkHelloActivity
#define _Included_com_easymorse_NdkHelloActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_easymorse_NdkHelloActivity
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_easymorse_NdkHelloActivity_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
